<a href="https://colab.research.google.com/github/AlflenGabriel/Otimizacao-algoritmo-genetico/blob/main/AlgoritmoGenetico1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
codItem = np.arange(1,11)
print("Códigos: ",codItem)
peso = np.array([5,6,2,20,3,21,1,11,13,2])
print("Pesos:", peso)
preco = np.array([20,10,470,600,225,650,590,270,430,350])
print("Preços", preco)
print("CodItem    Peso    Preço")
for i in range(10):
  print("{0}          {1}          {2}\n".format(codItem[i],peso[i],preco[i]))

Códigos:  [ 1  2  3  4  5  6  7  8  9 10]
Pesos: [ 5  6  2 20  3 21  1 11 13  2]
Preços [ 20  10 470 600 225 650 590 270 430 350]
CodItem    Peso    Preço
1          5          20

2          6          10

3          2          470

4          20          600

5          3          225

6          21          650

7          1          590

8          11          270

9          13          430

10          2          350



In [ ]:
capacidadeMochila = 35
tamanhoCadeiaGenetica = 10
tamanhoPopulacao = 8
print("Capacidade da mochila (kg): ", capacidadeMochila)
print("Tamanho do cromossomo (qtd. genes): ", tamanhoCadeiaGenetica)
print("Tamanho população: ", tamanhoPopulacao)

Capacidade da mochila (kg):  35
Tamanho do cromossomo (qtd. genes):  10
Tamanho população:  8


In [ ]:
populacaoInicial = np.random.randint(0,2, size=(tamanhoPopulacao, tamanhoCadeiaGenetica))
print("A populaçao inicial gerada aleatóriamente foi: ")
print(populacaoInicial)

A populaçao inicial gerada aleatóriamente foi: 
[[1 0 0 1 0 1 0 1 1 0]
 [1 0 1 0 1 0 0 0 1 0]
 [1 0 1 1 1 0 0 0 0 0]
 [0 1 0 0 1 1 1 1 0 0]
 [1 0 1 0 0 1 1 0 1 1]
 [1 1 0 0 1 1 1 0 0 1]
 [0 0 1 1 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 1 1]]


In [ ]:
def calculaFitness(populacao):
  fitness = np.zeros(tamanhoPopulacao)
  for i in range(tamanhoPopulacao):
    somaCusto = np.sum(populacao[i] * preco)
    #print("Populacao", populacao[i])
    #print("Preco", preco)
    somaPeso = np.sum(populacao[i] * peso)
    #print("Peso", peso)
    #print("Peso total", somaPeso)
    #print("********************")
    if somaPeso > capacidadeMochila:
      fitness[i] = 0
    else:
      fitness[i] = somaCusto
  return fitness

In [ ]:
fitnessCalculado = calculaFitness(populacaoInicial)
print("Fitness de cada cromossomo da população inicial:\n", fitnessCalculado)

Fitness de cada cromossomo da população inicial:
 [   0. 1145. 1315.    0.    0.    0.    0.  780.]


In [ ]:
def selecionarPais(populacao,fitness):
  fitnessPais = fitness
  pais = np.zeros((2,tamanhoCadeiaGenetica))
  print("Criação de dois cromossomos vazios\n:",pais)
  for i in range(2):
    maxFitnessCode = np.where(fitnessPais == np.max(fitnessPais))
    pais[i,:] = populacao[maxFitnessCode[0][0],:]
    fitnessPais[maxFitnessCode[0][0]] = -1
  return pais

In [ ]:
pais = selecionarPais(populacaoInicial,fitnessCalculado)
print("*********************************")
print("Cromossomos selecionados para reprodução:\n ",pais)

Criação de dois cromossomos vazios
: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
*********************************
Cromossomos selecionados para reprodução:
  [[1. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0. 0. 1. 0.]]


In [ ]:
def crossover(pais):
  filhos = np.zeros((2,tamanhoCadeiaGenetica))
  pontoCrossover = 3
  filhos[0,0:pontoCrossover] = pais[1,0:pontoCrossover]
  filhos[0,pontoCrossover:] = pais[0,pontoCrossover:]
  filhos[1,0:pontoCrossover] = pais[0,0:pontoCrossover]
  filhos[1,pontoCrossover:] = pais[1,pontoCrossover:]
  return filhos

In [ ]:
print(pais)
filhos= crossover(pais)
print("*********************************")
print(filhos)

[[1. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0. 0. 1. 0.]]
*********************************
[[1. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0. 0. 1. 0.]]


In [ ]:
import random as rd
def mutacao(filhos):
  txMutacao = 0.2 # taxa definida para mutação
  posicaoMutacao = 5 # posição na qual ocorrerá o bit-flip (mudança do bit)
  mutantesCandidatos = filhos
  for i in range(2):
    valRandomico = rd.random() # número sorteado pela função random() é entre 0 e 1
    print("Número randomico gerado pelo Python:", valRandomico)
    if valRandomico > txMutacao: # se o número for maior que a taxa, não haverá mutação
      continue
    else:
      print("Sorteado para mutação")
    #print("Cromossomo selecionado para mutação:", mutantesCandidatos[i,:])
    if mutantesCandidatos[i,posicaoMutacao] == 0:
      mutantesCandidatos[i,posicaoMutacao] = 1
    else:
      mutantesCandidatos[i,posicaoMutacao] = 0
  return mutantesCandidatos

In [ ]:
mutantes = mutacao(filhos)
print(mutantes)

Número randomico gerado pelo Python: 0.6020620900880405
Número randomico gerado pelo Python: 0.17768163327143371
Sorteado para mutação
[[1. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 1. 0. 0. 1. 0.]]


In [ ]:
def calculaFitnessIndividual(cromossomo):
  somaCusto = np.sum(cromossomo * preco)
  #print("Populacao", populacao[i])
  #print("Preco", preco)
  somaPeso = np.sum(cromossomo * peso)
  #print("Peso", peso)
  #print("Peso total", somaPeso)
  #print("********************")
  if somaPeso > capacidadeMochila:
    fitness = 0
  else:
    fitness = somaCusto
  return fitness

In [ ]:
print(calculaFitnessIndividual(pais[0]))

1315.0


In [ ]:
numGeracoes = 50 # número de reproduções que ocorrerá
populacao = populacaoInicial # popoulação inicial
for i in range(numGeracoes):
  fitnessPopulacaoAtual = calculaFitness(populacao)
  #selecionar pais para reprodução
  pais = selecionarPais(populacao,fitnessPopulacaoAtual)
  #Cruzamento dos pais para geração dos filhos
  filhos = crossover(pais)
  #Avaliar se os filhos sofrerão mutação
  filhos = mutacao(filhos)
  # Vamos armazenar a posição dos cromossomos com menor aptidão
  # para aplicarmos a estratégia elitisca, onde os cromossomos com menor aptidão serão
  # excluídos da população para que os filhos gerados tomem os seus lugares
  # identificacao da posição do cromossomo com menor aptidão (fitness)
  posicaoCromossomoMenorAptidao = np.where(fitnessPopulacaoAtual == np.amin(fitnessPopulacaoAtual))
  #print("Primeira posição de menor aptidão: ", posicaoCromossomoMenorAptidao[0][0])
  if (calculaFitnessIndividual(populacao[posicaoCromossomoMenorAptidao[0][0],:])<calculaFitnessIndividual(filhos[0,:])):
    populacao[posicaoCromossomoMenorAptidao[0][0],:]=filhos[0,:]
  #print("Populacao primeira substituicao: ", calculaFitness(populacao))
  # identificacao da posição do cromossomo com a segunda menor aptidão (fitness)
  fitnessPopulacaoAtual = calculaFitness(populacao)
  posicaoCromossomoSegundaMenorAptidao = np.where(fitnessPopulacaoAtual == np.amin(fitnessPopulacaoAtual))
  if (calculaFitnessIndividual(populacao[posicaoCromossomoSegundaMenorAptidao[0][0],:])<calculaFitnessIndividual(filhos[1,:])):
    populacao[posicaoCromossomoSegundaMenorAptidao[0][0],:]=filhos[1,:]
  #print("Primeira posição de menor aptidão: ", posicaoCromossomoSegundaMenorAptidao[0][0])
  #print("Populacao segunda substituicao: ", calculaFitness(populacao))
  fitnessPopulacaoAtual = calculaFitness(populacao) # calcula o fitness de cada cromossomo da população atual
  print("Populacao: ", calculaFitness(populacao))
print(populacao[0])
 # historicoFitness.append(fitnessPopulacaoAtual) # inclui o fitnesse no histórico




Criação de dois cromossomos vazios
: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Número randomico gerado pelo Python: 0.5344505155447294
Número randomico gerado pelo Python: 0.23541144696453342
Populacao:  [1145. 1315. 1315.    0.    0.    0.    0.  780.]
Criação de dois cromossomos vazios
: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Número randomico gerado pelo Python: 0.8097478555757789
Número randomico gerado pelo Python: 0.5866832752620432
Populacao:  [1145. 1315. 1315. 1315.    0.    0.    0.  780.]
Criação de dois cromossomos vazios
: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Número randomico gerado pelo Python: 0.7863656414905621
Número randomico gerado pelo Python: 0.040838134791457925
Sorteado para mutação
Populacao:  [1145. 1315. 1315. 1315.    0.    0.    0.  780.]
Criação de dois cromossomos vazios
: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Número randomico gerado pelo Python: 